# Attempt to spawn on safe materials
enable-safe-spawn: true

# Number of attempts to make before allowing an unsafe spawn
safe-spawn-attempts: 100

# Square radius of the spawn zone
spawn-radius: 10000

# Materials that are safe to spawn on
# See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for a list of materials
safe-materials:
  - BROWN_TERRACOTTA
  - COARSE_DIRT
  - COBBLESTONE
  - DIRT
  - GRASS_BLOCK
  - GRAVEL
  - ICE
  - LIGHT_GRAY_TERRACOTTA
  - ORANGE_TERRACOTTA
  - PACKED_ICE
  - PODZOL
  - RED_SAND
  - RED_TERRACOTTA
  - SAND
  - SNOW
  - STONE
  - TERRACOTTA
  - WHITE_TERRACOTTA
  - YELLOW_TERRACOTTA
